build: Fix -Werror={missing-declarations,old-style-definition}
../panel-plugin/calctest.c:18:6: error: no previous declaration for ‘interactive’ [-Werror=missing-declarations]
   18 | void interactive()
      |      ^~~~~~~~~~~
../panel-plugin/calctest.c: In function ‘interactive’:
../panel-plugin/calctest.c:18:6: error: old-style function definition [-Werror=old-style-definition]
cc1: all warnings being treated as errors