Fix missing-prototypes
calculator.c:67:6: error: no previous prototype for 'calc_save_config' [-Werror=missing-prototypes]

calculator.c:510:6: error: no previous prototype for 'calc_about' [-Werror=missing-prototypes]

Signed-off-by: Olaf Hering <olaf@aepfle.de>